version: "3.7"

services:
  interface_backend:
    image: interface_backend
    container_name: interface_backend
    restart: always
    ports:
      - 8088:8088
    volumes:
      - ./data_folder:/data_folder
      - ./backup_folder:/backup_folder
